# Generated by Django 4.1.1 on 2022-10-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_image_tag_created_at_alter_tag_name_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
