# Generated by Django 4.1.1 on 2022-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('summary', models.TextField(default='This is cool!')),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
